name: Java CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: 11
    - name: Grant execute permission for Gradlew
      run: chmod +x ./gradlew
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v1
      with:
        arguments: build --stacktrace
        distribution: 'wrapper'
    - name: Test with Gradle
      uses: gradle/gradle-build-action@v1
      with:
        distribution: 'wrapper'
        arguments: test --stacktrace
        
